# Generated by Django 4.2.6 on 2023-12-10 00:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalDataProvider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('logo', models.CharField(max_length=512, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128)),
                ('description', models.TextField(null=True)),
                ('active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('difficulty', models.IntegerField(null=True)),
                ('last_review_status', models.CharField(max_length=128, null=True)),
                ('last_review_by', models.CharField(max_length=128, null=True)),
                ('last_review_on', models.DateTimeField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studylens_models.resource')),
                ('isbn', models.CharField(max_length=13, null=True, unique=True)),
                ('authors', models.CharField(max_length=128, null=True)),
                ('publisher', models.CharField(max_length=128, null=True)),
                ('first_published_date', models.DateField(null=True)),
                ('last_published_date', models.DateField(null=True)),
                ('page_count', models.IntegerField(null=True)),
                ('language', models.CharField(default='English', max_length=128, null=True)),
            ],
            bases=('studylens_models.resource',),
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studylens_models.resource')),
                ('course_id', models.CharField(max_length=128, null=True, unique=True)),
                ('course_provider', models.CharField(max_length=128, null=True)),
                ('course_instructor', models.CharField(max_length=128, null=True)),
                ('course_free', models.BooleanField(default=False)),
                ('course_mode_of_instruction', models.CharField(choices=[('online-recorded', 'Online Recorded'), ('online-live', 'Online Live'), ('offline', 'Offline'), ('text', 'Text'), ('mix-text-video', 'Mix of Text and Video'), ('mix-text-video-interactivecode', 'Mix of Text, Video and Interactive Code'), ('mix-text-interactivecode', 'Mix of Text and Interactive Code')], max_length=128, null=True)),
                ('course_duration_scale', models.CharField(choices=[('hours', 'Hours'), ('days', 'Days'), ('weeks', 'Weeks'), ('months', 'Months'), ('years', 'Years')], max_length=128, null=True)),
                ('course_duration_value', models.IntegerField(null=True)),
                ('course_start_date', models.DateField(null=True)),
                ('course_end_date', models.DateField(null=True)),
                ('language', models.CharField(default='English', max_length=128, null=True)),
            ],
            bases=('studylens_models.resource',),
        ),
        migrations.CreateModel(
            name='Thumbnail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=500)),
                ('external_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studylens_models.externaldataprovider')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studylens_models.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=128)),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studylens_models.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Metric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metric_category', models.CharField(max_length=128, null=True)),
                ('metric_key', models.CharField(max_length=128, null=True)),
                ('metric_type', models.CharField(max_length=128, null=True)),
                ('metric_value', models.CharField(max_length=128, null=True)),
                ('metric_max', models.CharField(max_length=128, null=True)),
                ('external_provider', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studylens_models.externaldataprovider')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studylens_models.resource')),
            ],
        ),
        migrations.CreateModel(
            name='ExternalUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.CharField(max_length=512)),
                ('external_provider_service_type', models.CharField(choices=[('resource-purchase', 'Resource Purchase'), ('resource-view', 'Resource View')], max_length=128, null=True)),
                ('external_provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studylens_models.externaldataprovider')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='studylens_models.resource')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('resource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='studylens_models.resource')),
                ('video_id', models.CharField(max_length=128, null=True, unique=True)),
                ('video_provider', models.CharField(max_length=128, null=True)),
                ('channel', models.CharField(max_length=128, null=True)),
                ('upload_date', models.DateField(null=True)),
                ('duration', models.IntegerField(null=True)),
                ('language', models.CharField(default='English', max_length=128, null=True)),
                ('course_sequence', models.IntegerField(null=True)),
                ('course_instance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='studylens_models.course')),
            ],
            bases=('studylens_models.resource',),
        ),
    ]
